# config.py
import os
from pathlib import Path
from matplotlib.colors import LogNorm
from yt.units import K, mp, kb, mh, planck_constant, cm, m, s, g, erg

# Dataset-level block-mean downsampling applied at load time.  1 = no
# downsample (full native resolution).  2 = each axis ÷2 (volume ÷8); useful
# when the native dataset is too large to fit derived-field intermediates
# in RAM.  Domain dimensions must be divisible by this factor.
DOWNSAMPLE_FACTOR = 1

# --- Input/Output ---
# Repo root, used to build portable DEFAULT paths so nothing is hardcoded to one
# machine.  config.py lives at <repo>/src/quokka2s/pipeline/prep/config.py, so
# parents[4] == <repo>.  Override with QUOKKA_ROOT when the repo/data live
# elsewhere (e.g. an HPC cluster).  Every absolute default below derives from it
# and can be overridden individually by its own env var (see each line).
_PROJECT_ROOT = Path(os.environ.get("QUOKKA_ROOT", Path(__file__).resolve().parents[4]))

# Dataset selector.  Override per-process with the YT_DATASET env var so a
# *series* of snapshots can be looped without editing this file, e.g.
#   YT_DATASET=/path/to/plt0857000 \
#     python -m quokka2s.pipeline.tasks.run_pipeline --mode compute
# `_DATASET_BASENAME` (below) and `OUTPUT_DIR` derive from this, so each dataset
# lands in its own output dir and its own field-cache root — no collisions.
# Known snapshots on disk: plt263168 (old), plt0655228 (8GB), plt0857000.
YT_DATASET_PATH = os.environ.get(
    "YT_DATASET", str(_PROJECT_ROOT / "plt0655228"))  # default: plt0655228 (8GB)

# Both tables use the same (nH, NH, dVdr) schema and self-consistent T from
# DESPOTIC's iterateDust. Sphere builds with escapeProbGeom='sphere' (line
# fields are dVdr-invariant, broadcast across the dVdr axis); LVG uses the
# Sobolev escape probability with real dVdr-dependent line emission.
DESPOTIC_TABLE_PATH_LVG    = os.environ.get(
    "DESPOTIC_TABLE_LVG",    str(_PROJECT_ROOT / "output_tables_3D_GOW_LVG"    / "despotic_table.npz"))
DESPOTIC_TABLE_PATH_SPHERE = os.environ.get(
    "DESPOTIC_TABLE_SPHERE", str(_PROJECT_ROOT / "output_tables_3D_GOW_sphere" / "despotic_table.npz"))

# Switch via env var: `DESPOTIC_GEOM=sphere python -m quokka2s.pipeline.tasks.run_pipeline`
# Default = LVG so existing workflows are unchanged.
_DESPOTIC_GEOM = os.environ.get("DESPOTIC_GEOM", "LVG").lower()
_DATASET_BASENAME = os.path.basename(YT_DATASET_PATH)
# Output root for all figures + task_intermediates.  On a cluster point this at
# a writable mount (e.g. $SCRATCH) via QUOKKA_OUTPUT_ROOT.
_OUTPUT_ROOT = os.environ.get("QUOKKA_OUTPUT_ROOT", str(_PROJECT_ROOT / "output"))

# Path to pre-computed simulation sampling array (shape N×2: [log10(nH), log10(N_H)]).
# Generated by running: python -m quokka2s.pipeline.prep.snapshot_histogram

# --- Physics Parameters / Model Assumptions ---
# (2026-06-13) Removed T_CUTOFF / T_CUTOFF_DEFAULT and HIGH_T_4D_BLEND / T_QK_HIGH_K
# /  DESPOTIC_TABLE_4D_PATH_*.  Decision: no temperature gating on lumPerH and
# no 4D-table μγ branch.  The two-regime split for line luminosity is now done
# per species inside physics_fields (Hα uses Saha + T_QK in hot branch;
# C+ planned to follow the same pattern using CHIANTI/fiasco).

X_H = 0.74  # Mass fraction of Hydrogen
A_C = 1.6e-4  # gas-phase carbon abundance per H nucleus (GOW xC default; used by [C II])
A_LAMBDA_OVER_NH = 4e-22 * cm**2  # Dust extinction cross-section (mag * cm^2 / N_H)

# --- Simulation Control ---
PROJECTION_AXIS = 'x'     # Axis for projection ('x', 'y', or 'z')

# Lateral (x/y) box-exterior column extension.
# The simulation is a stratified shearing box (1 kpc × 1 kpc × ~few–8 kpc) sitting
# inside the MW disk at R≈8 kpc.  Its x/y faces are periodic BCs, not physical
# edges — the disk continues ~10 kpc beyond each face.  When computing
# column_density_H we add  L_ext × <n_H>(z)  along ±x and ±y, where <n_H>(z) is
# this snapshot's own (x,y)-averaged number density at the cell's height.
# ±z gets no extension (the 4–8 kpc box already spans the stratified disk
# beyond its scale heights).  Set to 0.0 to recover the original 6-face
# harmonic mean (no extension).
COLUMN_EXTENSION_LATERAL_KPC = 15.0
# Override via env: `LEXT_KPC=0 python -m quokka2s.pipeline.tasks.run_pipeline`
_lext_override = os.environ.get('LEXT_KPC')
if _lext_override is not None:
    COLUMN_EXTENSION_LATERAL_KPC = float(_lext_override)
# Optional RUN_TAG env adds a suffix to OUTPUT_DIR (e.g. RUN_TAG=v4 ->
# output/..._Lext15kpc_v4/) so re-runs don't overwrite earlier output dirs.
_RUN_TAG = os.environ.get('RUN_TAG', '')
_RUN_TAG_SUFFIX = f'_{_RUN_TAG}' if _RUN_TAG else ''

# How the 6 directional columns N_k are combined into column_density_H:
#   'harmonic'   -> 6 / Σ(1/N_k)   (min-dominated: effective shielding = thinnest direction)
#   'arithmetic' -> (1/6) Σ N_k    (plain mean of all 6 directions)
#   'max'        -> max_k N_k      (most-shielded / thickest direction)
#   'min'        -> min_k N_k      (least-shielded / thinnest direction)
# Folded into the cache key (cache.py) so each method keeps separate caches.
# Override via env: `COLDEN_MEAN=arithmetic python -m quokka2s.pipeline.tasks.run_pipeline`
COLUMN_DENSITY_MEAN = os.environ.get('COLDEN_MEAN', 'harmonic')

# OUTPUT_DIR is derived after COLUMN_EXTENSION_LATERAL_KPC so the directory
# name encodes the L_ext value — different L_ext runs land in sibling dirs
# (e.g. plt0655228_down1_Lext0kpc/ vs plt0655228_down1_Lext15kpc/) and do not
# overwrite each other.  task_intermediates/ lives inside, so cached compute
# results are separated cleanly as well.
_LEXT_TAG = f"_Lext{COLUMN_EXTENSION_LATERAL_KPC:g}kpc"
if _DESPOTIC_GEOM == "sphere":
    DESPOTIC_TABLE_PATH = DESPOTIC_TABLE_PATH_SPHERE
    OUTPUT_DIR = f"{_OUTPUT_ROOT}/{_DATASET_BASENAME}_down{DOWNSAMPLE_FACTOR}{_LEXT_TAG}_sphere{_RUN_TAG_SUFFIX}/"
else:
    DESPOTIC_TABLE_PATH = DESPOTIC_TABLE_PATH_LVG
    OUTPUT_DIR = f"{_OUTPUT_ROOT}/{_DATASET_BASENAME}_down{DOWNSAMPLE_FACTOR}{_LEXT_TAG}{_RUN_TAG_SUFFIX}/"

# --- Instrument / Observational Parameters ---
# Spectral resolving power R = λ/Δλ.  LSF FWHM (velocity) = c/R.
# Typical values: 1e3 (low-res, Δv≈300 km/s), 1e4 (mid, Δv≈30 km/s), 1e5 (ALMA, Δv≈3 km/s).
SPECTRAL_RESOLUTION_R = 1e6
# Spatial bin factor: n×n simulation cells → 1 instrument pixel (SUM reduce).
# Default 1 = native resolution (no binning).  4 means 4×4 cells per pixel.
SPATIAL_BIN = 4



# --- Plotting Parameters ---
FIGURE_UNITS = 'pc'
CMAP = 'viridis'

