# config.py
import os
from matplotlib.colors import LogNorm
from yt.units import K, mp, kb, mh, planck_constant, cm, m, s, g, erg

# Dataset-level block-mean downsampling applied at load time.  1 = no
# downsample (full native resolution).  2 = each axis ÷2 (volume ÷8); useful
# when the native dataset is too large to fit derived-field intermediates
# in RAM.  Domain dimensions must be divisible by this factor.
DOWNSAMPLE_FACTOR = 1

# --- Input/Output ---
# YT_DATASET_PATH = "/Users/baochen/quokka_postprocessing/plt263168" #old
YT_DATASET_PATH = "/Users/baochen/quokka_postprocessing/plt0655228" #new 8GB
# YT_DATASET_PATH = "/Users/baochen/quokka_postprocessing/plt0857000"

# Both tables use the same (nH, NH, dVdr) schema and self-consistent T from
# DESPOTIC's iterateDust. Sphere builds with escapeProbGeom='sphere' (line
# fields are dVdr-invariant, broadcast across the dVdr axis); LVG uses the
# Sobolev escape probability with real dVdr-dependent line emission.
DESPOTIC_TABLE_PATH_LVG    = "/Users/baochen/quokka_postprocessing/output_tables_3D_GOW_LVG/despotic_table.npz"
DESPOTIC_TABLE_PATH_SPHERE = "/Users/baochen/quokka_postprocessing/output_tables_3D_GOW_sphere/despotic_table.npz"

# Switch via env var: `DESPOTIC_GEOM=sphere python -m quokka2s.pipeline.tasks.run_pipeline`
# Default = LVG so existing workflows are unchanged.
_DESPOTIC_GEOM = os.environ.get("DESPOTIC_GEOM", "LVG").lower()
_DATASET_BASENAME = os.path.basename(YT_DATASET_PATH)
_OUTPUT_ROOT = "/Users/baochen/quokka_postprocessing/output"

# Path to pre-computed simulation sampling array (shape N×2: [log10(nH), log10(N_H)]).
# Generated by running: python -m quokka2s.pipeline.prep.snapshot_histgram
# LOG_SAMPLES_PATH = "/Users/baochen/quokka_postprocessing/quokka2s/src/log_samples.npy"

# --- Physics Parameters / Model Assumptions ---
# T_CUTOFF: lumPerH is zeroed above this temperature per species (K)
#
# Rationale: the GOW chemistry network (Gong, Ostriker & Wolfire 2017) only
# tracks singly-ionized states — carbon is locked in {C+, C, CO, CHx, HCO+}
# with NO C²⁺/C³⁺ reactions (GOW.py:45-47).  Above T ~ 5e4 K, CIE predicts
# carbon should start transitioning to C²⁺/C³⁺, but GOW keeps all C as C+,
# producing a spurious lumPerH plateau at 1e5–1e7 K.  The Janev H-ionization
# polynomial fit (GOW.py:449-458) is also only valid up to ~1e5 K.
# → 5e4 K is the network-physics upper limit for all species.
#
# Historical per-species values (kept in git / old output dirs for comparison):
#   CO:   100_000 K  (CO collisionally dissociates well before this anyway)
#   C+:   200_000 K  (too permissive; GOW network invalid above ~5e4 K)
#   HCO+: 100_000 K  (same as CO)
T_CUTOFF = {
    'CO':   2.0e7,
    'C+':   2.0e7,
    'HCO+': 2.0e7,
}
T_CUTOFF_DEFAULT = 2.0e7
X_H = 0.74  # Mass fraction of Hydrogen
A_LAMBDA_OVER_NH = 4e-22 * cm**2  # Dust extinction cross-section (mag * cm^2 / N_H)

# --- Simulation Control ---
PROJECTION_AXIS = 'x'     # Axis for projection ('x', 'y', or 'z')

# Lateral (x/y) box-exterior column extension.
# The simulation is a stratified shearing box (1 kpc × 1 kpc × ~few–8 kpc) sitting
# inside the MW disk at R≈8 kpc.  Its x/y faces are periodic BCs, not physical
# edges — the disk continues ~10 kpc beyond each face.  When computing
# column_density_H we add  L_ext × <n_H>(z)  along ±x and ±y, where <n_H>(z) is
# this snapshot's own (x,y)-averaged number density at the cell's height.
# ±z gets no extension (the 4–8 kpc box already spans the stratified disk
# beyond its scale heights).  Set to 0.0 to recover the original 6-face
# harmonic mean (no extension).
COLUMN_EXTENSION_LATERAL_KPC = 9.0

# OUTPUT_DIR is derived after COLUMN_EXTENSION_LATERAL_KPC so the directory
# name encodes the L_ext value — different L_ext runs land in sibling dirs
# (e.g. plt0655228_down2_Lext0kpc/ vs plt0655228_down2_Lext9kpc/) and do not
# overwrite each other.  task_intermediates/ lives inside, so cached compute
# results are separated cleanly as well.
_LEXT_TAG = f"_Lext{COLUMN_EXTENSION_LATERAL_KPC:g}kpc"
if _DESPOTIC_GEOM == "sphere":
    DESPOTIC_TABLE_PATH = DESPOTIC_TABLE_PATH_SPHERE
    OUTPUT_DIR = f"{_OUTPUT_ROOT}/{_DATASET_BASENAME}_down{DOWNSAMPLE_FACTOR}{_LEXT_TAG}_sphere/"
else:
    DESPOTIC_TABLE_PATH = DESPOTIC_TABLE_PATH_LVG
    OUTPUT_DIR = f"{_OUTPUT_ROOT}/{_DATASET_BASENAME}_down{DOWNSAMPLE_FACTOR}{_LEXT_TAG}/"

# --- Instrument / Observational Parameters ---
# Spectral resolving power R = λ/Δλ.  LSF FWHM (velocity) = c/R.
# Typical values: 1e3 (low-res, Δv≈300 km/s), 1e4 (mid, Δv≈30 km/s), 1e5 (ALMA, Δv≈3 km/s).
SPECTRAL_RESOLUTION_R = 1e6
# Spatial bin factor: n×n simulation cells → 1 instrument pixel (SUM reduce).
# Default 1 = native resolution (no binning).  4 means 4×4 cells per pixel.
SPATIAL_BIN = 4



# --- Plotting Parameters ---
FIGURE_UNITS = 'pc'
CMAP = 'viridis'


